#!/usr/bin/env bash
#Displays fizz multiple of 3, buzz multiple of 5, fizzzbuzz multiple of both
for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then 
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done
