#!/usr/bin/env bash
#Too many to count
PIDFILE="/tmp/myscript.pid"

# Cleanup function for SIGTERM and SIGQUIT
clean_up() {
    echo "I hate the kill command"
    rm -f "$PIDFILE"
    exit
}

# Signal handling
trap clean_up SIGTERM
trap clean_up SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

# Save PID
echo $$ > "$PIDFILE"

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
